# Week 5 - DS Automation Assignment - Michael Easton

## AI Use Disclosure:
To my knowledge I did not use AI to research, create, or complete any portion of this assignment; however, due to AI's integration into general internet searching functionality and many websites, it is possible debugging efforts may have inadvertantly included the use of AI. My intent is to primarily use source documentation for python, pandas, and other modules first before seeking answers through broader internet search.

# Instructions

## Task 1
Using our prepared churn data from week 2:
- use pycaret to find an ML algorithm that performs best on the data
    - Choose a metric you think is best to use for finding the best model; by default, it is accuracy but it could be AUC, precision, recall, etc. The week 3 FTE has some information on these different metrics.
- save the model to disk
- create a Python script/file/module with a function that takes a pandas dataframe as an input and returns the probability of churn for each row in the dataframe
    - your Python file/function should print out the predictions for new data (new_churn_data.csv)
    - the true values for the new data are [1, 0, 0, 1, 0] if you're interested
- test your Python module and function with the new data, new_churn_data.csv
- write a short summary of the process and results at the end of this notebook
- upload this Jupyter Notebook and Python file to a Github repository, and turn in a link to the repository in the week 5 assignment dropbox

Additional challenges:
- return the probability of churn for each new prediction, and the percentile where that prediction is in the distribution of probability predictions from the training dataset (e.g. a high probability of churn like 0.78 might be at the 90th percentile)
- use other autoML packages, such as TPOT, H2O, MLBox, etc, and compare performance and features with pycaret
- create a class in your Python module to hold the functions that you created
- accept user input to specify a file using a tool such as Python's `input()` function, the `click` package for command-line arguments, or a GUI
- Use the unmodified churn data (new_unmodified_churn_data.csv) in your Python script. This will require adding the same preprocessing steps from week 2 since this data is like the original unmodified dataset from week 1.


## Task 2: Critical Reflection
What are your observations based on the analyses you had performed? Is there one model that seems particularly useful for predicting churn. Why or why not?

# Task 1  Programming Steps

In [1]:
# Troubleshooting dependencies, attempting to create a new environment here.
#%conda create -n msds python=3.10.14 -y
#%conda init msds
#%conda activate msds

#%conda install pycaret
#python --version

#Setup a new environment for Python 3.11.9 for pycarat
#%conda install -c conda-forge pycaret -y
#%conda install scipy==1.11.4     #Noted that pycaret had trouble importing interp from scipy after 1.11.4 
#https://stackoverflow.com/questions/78008260/importerror-unable-to-import-interp-from-scipy-module
#%conda install scikit-learn==0.23.2 --force-reinstall

#Final Note: Creating a new environment via the command prompt vs. anaconda navigator seemed to work.
# After creation it only involved the installation of pycarat, but that seems like it was enough.

In [2]:
import pandas as pd

## Task 1.1 Pre-Processsed Data

In [3]:
#Importing the Churn Data from Week 2
df = pd.read_csv("churn_data.csv", index_col='customerID')
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7043 entries, 7590-VHVEG to 3186-AJIEK
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   tenure          7043 non-null   int64
 1   PhoneService    7043 non-null   object
 2   Contract        7043 non-null   object
 3   PaymentMethod   7043 non-null   object
 4   MonthlyCharges  7043 non-null   float64
 5   TotalCharges    7032 non-null   float64
 6   Churn           7043 non-null   object
dtypes: float64(2), int64(1), object(4)
memory usage: 440.2+ KB

In [4]:
new_df = pd.read_csv("new_churn_data.csv", index_col='customerID')
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 9305-CKSKC to 6348-TACGU
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   tenure             5 non-null      int64
 1   PhoneService       5 non-null      int64
 2   Contract           5 non-null      int64
 3   PaymentMethod      5 non-null      int64
 4   MonthlyCharges     5 non-null      float64
 5   TotalCharges       5 non-null      float64
 6   charge_per_tenure  5 non-null      float64
dtypes: float64(3), int64(4)
memory usage: 320.0+ bytes

In [5]:
# Need to create the "Charge_Per_Tenure" column category to match the datasets and make the rest numerical.
df['charge_per_tenure'] = df['TotalCharges']/df['tenure']
df['Contract'] = df['Contract'].replace({'Month-to-month': 0, 'One year': 1, 'Two year': 2})
df['PaymentMethod'] = df['PaymentMethod'].replace({'Credit card (automatic)': 0, 'Bank transfer (automatic)':1, 'Mailed check':2, 'Electronic check':3})
df['PhoneService'] = df['PhoneService'].replace({'Yes':1,'No':0})
df['Churn'] = df['Churn'].replace({'Yes':1,'No':0})
df = df[df['TotalCharges'].isna()==False]

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 7590-VHVEG to 3186-AJIEK
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   tenure             7032 non-null   int64
 1   PhoneService       7032 non-null   int64
 2   Contract           7032 non-null   int64
 3   PaymentMethod      7032 non-null   int64
 4   MonthlyCharges     7032 non-null   float64
 5   TotalCharges       7032 non-null   float64
 6   Churn              7032 non-null   int64
 7   charge_per_tenure  7032 non-null   float64
dtypes: float64(3), int64(5)
memory usage: 494.4+ KB

### 1.1.1 PyCaret Pre-Processed

In [6]:
from pycaret.classification import setup, compare_models, predict_model, save_model, load_model

In [34]:
dfList = list(df.columns)
dfList.remove("Churn")
dfList
pc_automl = setup(data = df, target = "Churn", preprocess = False)
#, numeric_features = dfList, fold_shuffle = True)

Metric Explanations for Future Reference:

- Accuracy - % of how many Non-Churn cases were actually predicted as Non-Churn
- Recall - % of how many Churn cases were predicted to Churn
- Precision - % of how many Churn & Non-Churn cases were correctly predicted
- AUC - Area under the curve of ROC (True Positive vs. False Positive rate) - High shows catching all positives and having no false negatives
- F1 - Harmonic Mean of Recall & Precision (High is good) - 
- Kappa - Cohen's Kappa compares accuracy against random chance and is a potentially better accuracy measure in unbalanced data (like this data)
- MCC (Matthews Correlation Coefficient) - If all four measures of the confusion matrix are high, MCC will be high.
- TT(Sec) - Relative time to run the model

Ref: 
- https://www.drivedatascience.com/model-evaluation-confusion-matrix-precision-recall-f1-roc-auc-cross-validation/
- https://www.statisticshowto.com/matthews-correlation-coefficient/
- https://www.geeksforgeeks.org/machine-learning/f1-score-in-machine-learning/
- https://karam-nus.github.io/metrics/docs/metrics/classification/cohens_kappa

In [35]:
recall_model = compare_models(sort = 'Recall')
recall_model

QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
                              store_covariance=False, tol=0.0001)

In [53]:
from pycaret.classification import create_model
QDA_setup = setup(data=df, target='Churn', preprocess = False)
QDA_model = create_model('qda')

In [54]:
save_model(QDA_model, 'QDA_Churn')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('placeholder', None),
                 ('trained_model',
                  QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
                                                store_covariance=False,
                                                tol=0.0001))],
          verbose=False),
 'QDA_Churn.pkl')

In [55]:
kappa_model = compare_models(sort ='Kappa')
kappa_model

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=511, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [39]:
LR_setup = setup(data=df, target='Churn')
LR_model = create_model('lr')

In [40]:
df.iloc[-2:-1]

,tenure,PhoneService,Contract,PaymentMethod,MonthlyCharges,TotalCharges,Churn,charge_per_tenure
customerID,,,,,,,,
8361-LTMKD,4,1,0,2,74.4,306.6,1,76.65

In [41]:
predict_model(LR_model, df.iloc[-2:-1])

,tenure,PhoneService,Contract,PaymentMethod,MonthlyCharges,TotalCharges,charge_per_tenure,Churn,prediction_label,prediction_score
customerID,,,,,,,,,,
8361-LTMKD,4,1,0,2,74.400002,306.600006,76.650002,1,1,0.5779

In [56]:
save_model(LR_model, 'LR_Churn')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('placeholder', None),
                 ('trained_model',
                  LogisticRegression(C=1.0, class_weight=None, dual=False,
                                     fit_intercept=True, intercept_scaling=1,
                                     l1_ratio=None, max_iter=1000,
                                     multi_class='auto', n_jobs=None,
                                     penalty='l2', random_state=3940,
                                     solver='lbfgs', tol=0.0001, verbose=0,
                                     warm_start=False))],
          verbose=False),
 'LR_Churn.pkl')

In [43]:
import pickle
with open('LR_Churn_Model.pk', 'wb') as f:
    pickle.dump(kappa_model, f)

In [44]:
with open('LR_Churn_Model.pk', 'rb') as f:
    loaded_model = pickle.load(f)

In [45]:
nChurnDF = df.iloc[-2:-1].copy()
nChurnDF.drop('Churn', axis=1, inplace=True)
loaded_model.predict(nChurnDF)

array([1], dtype=int8)

In [46]:
loaded_nb = load_model("LR_Churn")

Transformation Pipeline and Model Successfully Loaded

In [47]:
predict_model(loaded_nb, nChurnDF)

,tenure,PhoneService,Contract,PaymentMethod,MonthlyCharges,TotalCharges,charge_per_tenure,prediction_label,prediction_score
customerID,,,,,,,,,
8361-LTMKD,4,1,0,2,74.400002,306.600006,76.650002,1,0.5779

In [48]:
predict_model(loaded_model)

,tenure,PhoneService,Contract,PaymentMethod,MonthlyCharges,TotalCharges,charge_per_tenure,Churn,prediction_label,prediction_score
customerID,,,,,,,,,,
8778-LMWTJ,9,1,0,3,74.849998,708.200012,78.688889,0,1,0.5706
1193-RTSLK,38,1,0,0,83.900002,3233.600098,85.094734,1,0,0.7308
1707-HABPF,46,1,1,1,91.300003,4126.350098,89.703262,0,0,0.8580
2507-QZPQS,15,1,0,3,95.699997,1451.099976,96.739998,0,1,0.6736
5429-LWCMV,12,1,0,3,89.150002,1057.550049,88.129166,0,1,0.6475
...,...,...,...,...,...,...,...,...,...,...
0526-SXDJP,72,0,2,1,42.099998,2962.000000,41.138889,0,0,0.9928
3011-WQKSZ,19,1,0,3,20.000000,377.549988,19.871052,0,0,0.8649
1471-GIQKQ,1,1,0,3,49.950001,49.950001,49.950001,0,0,0.5338
3745-HRPHI,66,0,2,1,54.650002,3632.000000,55.030304,0,0,0.9835
9391-TTOYH,23,1,0,2,19.500000,470.200012,20.443478,0,0,0.9058

In [57]:
from IPython.display import Code

Code('ChurnModel.py')

# -*- coding: utf-8 -*-
"""
Spyder Editor

This is a temporary script file.
"""

class ChurnModel:
    """
    Modified functions from Week 5 FTE, expanded to be a class and include additional
    information.
    Load Data, Make a Prediction (Pre-Processed), Present Prediction and
    probabilities.
    Defaults to Pre-Proccessed Data (PPD) = True. Currently only works with
    Pre-Processed Data.
    """

    def __init__(self, filepath, bestmodel, PPD = True, last_prediction = None):
        self.filepath = filepath
        self.bestmodel = bestmodel
        self.PPD = PPD
        self.last_prediction = last_prediction

    def develop_predictions(self):
        import pandas as pd
        from pycaret.classification import predict_model, load_model

        def load_data(filepath):
            """
            Loads Churn data into a DataFrame from a string filepath.
            """
            df = pd.read_csv(filepath, index_col='customerID')
            return df

        def make_predictions(self, mpdf):
            """
            Uses the pycaret best model to make predictions on data in the df dataframe.
            """
            model = load_model(self.bestmodel)
            mppredictions = predict_model(model, data=mpdf)

            # Check the column names
            print(mppredictions.columns)

            # Rename 'prediction_label' to 'Churn_prediction' if it exists
            if 'prediction_label' in mppredictions.columns:
                mppredictions.rename(columns={'prediction_label': 'Churn_Prediction', 'prediction_score':'Churn_Probability'}, inplace=True)

                # Replace values in the new column
                mppredictions['Churn_Prediction'].replace({1: 'Churn', 0: 'No Churn'}, inplace=True)

                #Add a new Column with the Prediction Percentages
                if self.PPD == True:
                    return mppredictions.drop(['tenure','PhoneService','Contract','PaymentMethod','MonthlyCharges','TotalCharges','charge_per_tenure'], axis=1)
                else:
                    return mppredictions.drop(['tenure','PhoneService','Contract','PaymentMethod','MonthlyCharges','TotalCharges'], axis=1)
            else:
                raise KeyError("The 'prediction_label' column was not found in the predictions DataFrame")


        df = load_data(self.filepath)
        self.last_prediction = make_predictions(self,df)

    def show_prediction(self):
        print("Prediction:")
        print(self.last_prediction)

In [58]:
%run ChurnModel.py

In [59]:
CM = ChurnModel('new_churn_data.csv','LR_Churn')
CM.develop_predictions()
CM.show_prediction()

Transformation Pipeline and Model Successfully Loaded

Index(['tenure', 'PhoneService', 'Contract', 'PaymentMethod', 'MonthlyCharges',
       'TotalCharges', 'charge_per_tenure', 'prediction_label',
       'prediction_score'],
      dtype='object')
Prediction:
           Churn_Prediction  Churn_Probability
customerID
9305-CKSKC            Churn             0.5449
1452-KNGVK         No Churn             0.5586
6723-OKKJM         No Churn             0.9439
7832-POPKP         No Churn             0.8364
6348-TACGU         No Churn             0.5522

[1, 0, 0, 1, 0]

In [60]:
DM = ChurnModel('new_churn_data.csv','QDA_Churn')
DM.develop_predictions()
DM.show_prediction()

Transformation Pipeline and Model Successfully Loaded

Index(['tenure', 'PhoneService', 'Contract', 'PaymentMethod', 'MonthlyCharges',
       'TotalCharges', 'charge_per_tenure', 'prediction_label',
       'prediction_score'],
      dtype='object')
Prediction:
           Churn_Prediction  Churn_Probability
customerID
9305-CKSKC            Churn                1.0
1452-KNGVK            Churn                1.0
6723-OKKJM            Churn                1.0
7832-POPKP            Churn                1.0
6348-TACGU            Churn                1.0

## Task 1.2 Non-Processed Data

In [26]:
u_df = pd.read_csv("churn_data.csv", index_col='customerID')
u_df.info()
u_newdf = pd.read_csv("new_churn_data_unmodified.csv", index_col = 'customerID')
u_newdf.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7043 entries, 7590-VHVEG to 3186-AJIEK
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   tenure          7043 non-null   int64
 1   PhoneService    7043 non-null   object
 2   Contract        7043 non-null   object
 3   PaymentMethod   7043 non-null   object
 4   MonthlyCharges  7043 non-null   float64
 5   TotalCharges    7032 non-null   float64
 6   Churn           7043 non-null   object
dtypes: float64(2), int64(1), object(4)
memory usage: 440.2+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 9305-CKSKC to 6348-TACGU
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   tenure          5 non-null      int64
 1   PhoneService    5 non-null      object
 2   Contract        5 non-null      object
 3   PaymentMethod   5 non-null      object
 4   MonthlyCharges  5 non-null      float64
 5   TotalCharges    5 non-null      float64
dtypes: float64(2), int64(1), object(3)
memory usage: 280.0+ bytes

### 1.2.1 PyCaret Non-Pre-Processed

In [27]:
u_dfList = list(u_df.columns)
u_dfList.remove("Churn")
u_dfList
u_pc_automl = setup(data = u_df, target = "Churn")

In [28]:
u_model = compare_models(sort = 'Recall')
u_model

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=7792, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [29]:
ADA_setup = setup(data=u_df, target='Churn')
ADA_model = create_model('ada')

In [30]:
save_model(ADA_model, 'ADA_Model')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('label_encoding',
                  TransformerWrapperWithInverse(exclude=None, include=None,
                                                transformer=LabelEncoder())),
                 ('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     include=['tenure', 'MonthlyCharges',
                                              'TotalCharges'],
                                     transformer=SimpleImputer(add_indicator=False,
                                                               copy=True,
                                                               fill_value=None,
                                                               keep_empty_features=False,...
                                     include=['Contract', 'PaymentMethod'],
                                     transformer=OneHotEncoder(cols=['Contract',
                                                                     'PaymentMethod'],
                                                               drop_invariant=False,
                                                               handle_missing='return_nan',
                                                               handle_unknown='value',
                                                               return_df=True,
                                                               use_cat_names=True,
                                                               verbose=0))),
                 ('trained_model',
                  AdaBoostClassifier(algorithm='SAMME.R', estimator=None,
                                     learning_rate=1.0, n_estimators=50,
                                     random_state=3117))],
          verbose=False),
 'ADA_Model.pkl')

In [31]:
loaded_npp = load_model("ADA_Model")
u_nChurnDF = df.iloc[-2:-1].copy()
u_nChurnDF.drop('Churn', axis=1, inplace=True)
predict_model(loaded_npp, u_nChurnDF)

Transformation Pipeline and Model Successfully Loaded

,tenure,PhoneService,Contract,PaymentMethod,MonthlyCharges,TotalCharges,charge_per_tenure,prediction_label,prediction_score
customerID,,,,,,,,,
8361-LTMKD,4,1,0,2,74.400002,306.600006,76.650002,No,0.5064

In [32]:
AM = ChurnModel("new_churn_data_unmodified.csv","ADA_Model", PPD =False)

In [33]:
AM.develop_predictions()
AM.show_prediction()

Transformation Pipeline and Model Successfully Loaded

Index(['tenure', 'PhoneService', 'Contract', 'PaymentMethod', 'MonthlyCharges',
       'TotalCharges', 'prediction_label', 'prediction_score'],
      dtype='object')
Prediction:
           Churn_Prediction  Churn_Probability
customerID
9305-CKSKC              Yes             0.5048
1452-KNGVK               No             0.5066
6723-OKKJM               No             0.5117
7832-POPKP              Yes             0.5008
6348-TACGU               No             0.5169

# Summary

This week, I practiced using the AutoML feature of the module pycarat to compare and create a model, save it, then load it back in to predict Churn on a set of new data. For the first task I attempted to pre-process churn_data; however, I quickly realized that the churn_data and new_churn_data featured different features that needed to be remedied. In converting categorical data to numerical, I also realized that I did not know with what methods the new_churn_data was converted to numerical data. Comparing values between these two spreadsheets and new_churn_data_unmodified it appeared that at least Payment Type didn't follow a discernable pattern. 

With this possible issue noted, I still progressed in creating models with this cleaned up churn_data, focusing on the measures of Recall,as this might estimate the Churned accounts better, and Kappa, which is a similar measure to accuracy with improvements in how it handles unbalanced data like the churn set. In doing this I followed the process chain for both models (except only creating one pickle file based on the Logistic Regression model). This yielded a Linear Regression Model and a Quadratic Discriminat Analysis Model. 

A third model was created using unprocessed data. I had to do some minor clean-up but in general it was a simpler process. This yielded a Gradient Boosting Classifier model.

With these three models, I created Python script to more generalize input and prediction of new data. This came in the form of Python class object called ChurnModel which takes in the new data set, the name of the saved model, and whether or not the data was Pre-Processed/Pre-Cleaned. Running the develop_prediction method in this object creates a set of prediction results for the input data that is stored in the Model object as a last_prediction. In the future it may be useful to have this last_prediction variable store a longer history to monitor the performance of the model over time.

The results of each model are below:

**Cleaned Data**
| Quadratic Discriminant Analysis | Churn Actual | Prediction | Probability |
| --- | --- | --- | --- |
| --- | 1 | Churn | 1.0 |
| --- | 0 | Churn | 1.0 |
| --- | 0 | Churn | 1.0 |
| --- | 1 | Churn | 1.0 |
| --- | 0 | Churn | 1.0 |

| Logistic Regression | Churn Actual | Prediction | Probability |
| --- | --- | --- | --- |
| --- | 1 | Churn | 0.5449 |
| --- | 0 | No Churn | 0.5586 |
| --- | 0 | No Churn | 0.9439 |
| --- | 1 | No Churn | 0.8364 |
| --- | 0 | No Churn | 0.5522 |

**Raw Data**
| Gradient Boosting Classifier | Churn Actual | Prediction | Probability |
| --- | --- | --- | --- |
| --- | 1 | Churn | 0.5048 |
| --- | 0 | No Churn | 0.5066 |
| --- | 0 | No Churn | 0.5117 |
| --- | 1 | Churn | 0.5008 |
| --- | 0 | No Churn | 0.5169 |

Gradient Boosting Classifier got 100% on it's prediction of the data; however, looking at the probabilities it seems as if it'd be close to a 50-50 shot. Logistic Regression, presented probabilities that were more "certain" of their result but it did not catch the 2nd Churn case. It instead featured a high probability that case was a No Churn Case. That said, it appears Logistic Regression might fit the data better, but I would need to confirm the way in which the new_churn_data was cleaned to ensure it matches how the training data was cleaned. There was a difference in the categorical variables that could present a problem that the Gradient Boosting Classifier didn't need to accomodate.